class TestHash {

	public static void main(String[] args) {
	
		TestHash t1 = new TestHash();
		System.out.println(t1.hashCode());

		TestHash t2 = new TestHash();
		System.out.println(t2.hashCode());
	}
}

// hashCode() will return an unique id depending upon address generated by JVM for saving the objects in hashing related data structures 
// so that searching is easy.

// searching -> HashCode -> O(1) -> best searching result.

// we can also override the hashCode() method as we desire